#!/usr/bin/env bash

# Keep product build flags aligned with the product CI workflow.
GAMEGO_PRODUCT=1
HAVE_HANDHELD_RUNTIME=1
HAVE_HANDHELD_QUICK_MENU=1
P1B2_VALIDATION_APK=0
HAVE_HANDHELD_RUNTIME_TEST_HARNESS=0
HAVE_GAMEGO_E2E_HARNESS=0
GAMEGO_PACKAGE=com.retroarch.aarch64
GAMEGO_APP_NAME='RetroArch (AArch64)'
GAMEGO_ABI=arm64-v8a
GAMEGO_DEVICE_SERIAL_DEFAULT=2419TNW44608
